controller_frequency: 5.0

TrajectoryPlannerROS:
  max_vel_x: 10.0
  min_vel_x: 0.0
  max_vel_theta: 0.20
  min_vel_theta: -0.20
  min_in_place_vel_theta: 0.0

  acc_lim_theta: 0.1
  acc_lim_x: 2.5
  acc_lim_y: 0

  escape_vel: -2
  holonomic_robot: false
  
  sim_granularity: 0.5
  angular_sim_granularity: 0.05
  
  vx_samples: 30
  vth_samples: 60
  sim_time: 2
  
  xy_goal_tolerance: 1.0
  latch_xy_goal_tolerance: false
