local_costmap:
  global_frame: cora/odom
  robot_base_frame: cora/base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 250.0
  height: 200.0
  resolution: 1.0
